name: Deploy to Cloud SDK
on:
  workflow_dispatch:
    
  pull_request:
    branches:
      - master
      - develop
      - feature/cloud/sdk


defaults:
  run:
    shell: bash

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{secrets.PROJECT_ID}}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
     
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gcloud CLI
        run: gcloud storage buckets list --project ${{secrets.PROJECT_ID}} --format=json
      
      - name: 'Use gcloud CLI'
        run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'
