name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      
    - name: Run tests
      run: |
        pytest